Config = {}
Config.Locale = "en"

Config.Weapons = {
  WEAPON_KNIFE = { item = 'knife', label = _U('weapon_knife') },
  WEAPON_NIGHTSTICK = { item = 'nightstick', label = _U('weapon_nightstick') },
  WEAPON_HAMMER = { item = 'hammer', label = _U('weapon_hammer') },
  WEAPON_BAT = { item = 'bat', label = _U('weapon_bat') },
  WEAPON_GOLFCLUB = { item = 'golfclub', label = _U('weapon_golfclub') },
  WEAPON_CROWBAR = { item = 'crowbar', label = _U('weapon_crowbar') },
  WEAPON_PISTOL = { item = 'pistol', label = _U('weapon_pistol') },
  WEAPON_COMBATPISTOL = { item = 'combatpistol', label = _U('weapon_combatpistol') },
  WEAPON_APPISTOL = { item = 'appistol', label = _U('weapon_appistol') },
  WEAPON_PISTOL50 = { item = 'pistol50', label = _U('weapon_pistol50') },
  WEAPON_MICROSMG = { item = 'microsmg', label = _U('weapon_microsmg') },
  WEAPON_SMG = { item = 'smg', label = _U('weapon_smg') },
  WEAPON_ASSAULTSMG = { item = 'assaultsmg', label = _U('weapon_assaultsmg') },
  WEAPON_ASSAULTRIFLE = { item = 'assaultrifle', label = _U('weapon_assaultrifle') },
  WEAPON_CARBINERIFLE = { item = 'carbinerifle', label = _U('weapon_carbinerifle') },
  WEAPON_ADVANCEDRIFLE = { item = 'advancedrifle', label = _U('weapon_advancedrifle') },
  WEAPON_MG = { item = 'mg', label = _U('weapon_mg') },
  WEAPON_COMBATMG = { item = 'combatmg', label = _U('weapon_combatmg') },
  WEAPON_PUMPSHOTGUN = { item = 'pumpshotgun', label = _U('weapon_pumpshotgun') },
  WEAPON_SAWNOFFSHOTGUN = { item = 'sawnoffshotgun', label = _U('weapon_sawnoffshotgun') },
  WEAPON_ASSAULTSHOTGUN = { item = 'assaultshotgun', label = _U('weapon_assaultshotgun') },
  WEAPON_BULLPUPSHOTGUN = { item = 'bullpupshotgun', label = _U('weapon_bullpupshotgun') },
  WEAPON_STUNGUN = { item = 'stungun', label = _U('weapon_stungun') },
  WEAPON_SNIPERRIFLE = { item = 'sniperrifle', label = _U('weapon_sniperrifle') },
  WEAPON_HEAVYSNIPER = { item = 'heavysniper', label = _U('weapon_heavysniper') },
  WEAPON_REMOTESNIPER = { item = 'remotesniper', label = _U('weapon_remotesniper') },
  WEAPON_GRENADELAUNCHER = { item = 'grenadelauncher', label = _U('weapon_grenadelauncher') },
  WEAPON_RPG = { item = 'rpg', label = _U('weapon_rpg') },
  WEAPON_STINGER = { item = 'stinger', label = _U('weapon_stinger') },
  WEAPON_MINIGUN = { item = 'minigun', label = _U('weapon_minigun') },
  WEAPON_GRENADE = { item = 'grenade', label = _U('weapon_grenade') },
  WEAPON_STICKYBOMB = { item = 'stickybomb', label = _U('weapon_stickybomb') },
  WEAPON_SMOKEGRENADE = { item = 'smokegrenade', label = _U('weapon_smokegrenade') },
  WEAPON_BZGAS = { item = 'bzgas', label = _U('weapon_bzgas') },
  WEAPON_MOLOTOV = { item = 'molotov', label = _U('weapon_molotov') },
  WEAPON_FIREEXTINGUISHER = { item = 'fireextinguisher', label = _U('weapon_fireextinguisher') },
  WEAPON_PETROLCAN = { item = 'petrolcan', label = _U('weapon_petrolcan') },
  WEAPON_DIGISCANNER = { item = 'digiscanner', label = _U('weapon_digiscanner') },
  WEAPON_BALL = { item = 'ball', label = _U('weapon_ball') },
  WEAPON_SNSPISTOL = { item = 'snspistol', label = _U('weapon_snspistol') },
  WEAPON_BOTTLE = { item = 'bottle', label = _U('weapon_bottle') },
  WEAPON_GUSENBERG = { item = 'gusenberg', label = _U('weapon_gusenberg') },
  WEAPON_SPECIALCARBINE = { item = 'specialcarbine', label = _U('weapon_specialcarbine') },
  WEAPON_HEAVYPISTOL = { item = 'heavypistol', label = _U('weapon_heavypistol') },
  WEAPON_BULLPUPRIFLE = { item = 'bullpuprifle', label = _U('weapon_bullpuprifle') },
  WEAPON_DAGGER = { item = 'dagger', label = _U('weapon_dagger') },
  WEAPON_VINTAGEPISTOL = { item = 'vintagepistol', label = _U('weapon_vintagepistol') },
  WEAPON_FIREWORK = { item = 'firework', label = _U('weapon_firework') },
  --WEAPON_MUSKET = { item = 'musket', label = _U('weapon_musket') },
  WEAPON_HEAVYSHOTGUN = { item = 'heavyshotgun', label = _U('weapon_heavyshotgun') },
  WEAPON_MARKSMANRIFLE = { item = 'marksmanrifle', label = _U('weapon_marksmanrifle') },
  WEAPON_HOMINGLAUNCHER = { item = 'hominglauncher', label = _U('weapon_hominglauncher') },
  WEAPON_PROXMINE = { item = 'proxmine', label = _U('weapon_proxmine') },
  WEAPON_SNOWBALL = { item = 'snowball', label = _U('weapon_snowball') },
  WEAPON_FLAREGUN = { item = 'flaregun', label = _U('weapon_flaregun') },
  WEAPON_GARBAGEBAG = { item = 'garbagebag', label = _U('weapon_garbagebag') },
  WEAPON_HANDCUFFS = { item = 'handcuffs', label = _U('weapon_handcuffs') },
  WEAPON_COMBATPDW = { item = 'combatpdw', label = _U('weapon_combatpdw') },
  WEAPON_MARKSMANPISTOL = { item = 'marksmanpistol', label = _U('weapon_marksmanpistol') },
  WEAPON_KNUCKLE = { item = 'knuckle', label = _U('weapon_knuckle') },
  WEAPON_HATCHET = { item = 'hatchet', label = _U('weapon_hatchet') },
  WEAPON_RAILGUN = { item = 'railgun', label = _U('weapon_railgun') },
  WEAPON_MACHETE = { item = 'machete', label = _U('weapon_machete') },
  WEAPON_MACHINEPISTOL = { item = 'machinepistol', label = _U('weapon_machinepistol') },
  WEAPON_SWITCHBLADE = { item = 'switchblade', label = _U('weapon_switchblade') },
  WEAPON_REVOLVER = { item = 'revolver', label = _U('weapon_revolver') },
  WEAPON_DBSHOTGUN = { item = 'dbshotgun', label = _U('weapon_dbshotgun') },
  WEAPON_COMPACTRIFLE = { item = 'compactrifle', label = _U('weapon_compactrifle') },
  WEAPON_AUTOSHOTGUN = { item = 'autoshotgun', label = _U('weapon_autoshotgun') },
  WEAPON_BATTLEAXE = { item = 'battleaxe', label = _U('weapon_battleaxe') },
  WEAPON_COMPACTLAUNCHER = { item = 'compactlauncher', label = _U('weapon_compactlauncher') },
  WEAPON_MINISMG = { item = 'minismg', label = _U('weapon_minismg') },
  WEAPON_PIPEBOMB = { item = 'pipebomb', label = _U('weapon_pipebomb') },
  WEAPON_POOLCUE = { item = 'poolcue', label = _U('weapon_poolcue') },
  WEAPON_WRENCH = { item = 'wrench', label = _U('weapon_wrench') },
  WEAPON_FLASHLIGHT = { item = 'flashlight', label = _U('weapon_flashlight') },
  GADGET_NIGHTVISION = { item = 'nightvision', label = _U('gadget_nightvision') },
  GADGET_PARACHUTE = { item = 'parachute', label = _U('gadget_parachute') },
  WEAPON_FLARE = { item = 'flare', label = _U('weapon_flare') }, 
  WEAPON_SNSPISTOL_MK2 = { item = 'snspistol_mk2', label = _U('weapon_snspistol_mk2') }, 
  WEAPON_REVOLVER_MK2 = { item = 'revolver_mk2', label = _U('weapon_revolver_mk2') },  
  WEAPON_DOUBLEACTION = { item = 'doubleaction', label = _U('weapon_doubleaction') },    
  WEAPON_SPECIALCARBINE_MK2 = { item = 'specialcarbine_mk2', label = _U('weapon_specialcarabine_mk2') },  
  WEAPON_BULLPUPRIFLE_MK2 = { item = 'bullpuprifle_mk2', label = _U('weapon_bullpruprifle_mk2') },   
  WEAPON_PUMPSHOTGUN_MK2 = { item = 'pumpshotgun_mk2', label = _U('weapon_pumpshotgun_mk2') },
  WEAPON_MARKSMANRIFLE_MK2 = { item = 'marksmanrifle_mk2', label = _U('weapon_marksmanrifle_mk2') },  
  WEAPON_ASSAULTRIFLE_MK2 = { item = 'assaultrifle_mk2', label = _U('weapon_assaultrifle_mk2') },
  WEAPON_CARBINERIFLE_MK2 = { item = 'carbinerifle_mk2', label = _U('weapon_carbinerifle_mk2') },  
  WEAPON_COMBATMG_MK2 = { item = 'combatmg_mk2', label = _U('weapon_combatmg_mk2') },   
  WEAPON_HEAVYSNIPER_MK2 = { item = 'heavysniper_mk2', label = _U('weapon_heavysniper_mk2') },   
  WEAPON_PISTOL_MK2 = { item = 'pistol_mk2', label = _U('weapon_pistol_mk2') },   
  WEAPON_SMG_MK2 = { item = 'smg_mk2', label = _U('weapon_smg_mk2') }
}

Config.AmmoTypes = {
  AMMO_PISTOL = { item = 'pistol_ammo' },
  AMMO_SMG = { item = 'smg_ammo' },
  AMMO_FIREWORK = { item = 'firework_ammo' },
  AMMO_RIFLE = { item = 'rifle_ammo' },
  AMMO_MG = { item = 'mg_ammo' },
  AMMO_SHOTGUN = { item = 'shotgun_ammo' },
  AMMO_STUNGUN = { item = 'stungun_ammo' },
  AMMO_SNIPER = { item = 'sniper_ammo' },
  AMMO_SNIPER_REMOTE = { item = 'sniper_remote_ammo' },
  AMMO_MINIGUN = { item = 'minigun_ammo' },
  AMMO_GRENADELAUNCHER = { item = 'grenadelauncher_ammo' },
  AMMO_GRENADELAUNCHER_SMOKE = { item = 'grenadelauncher_smoke_ammo' },
  AMMO_RPG = { item = 'rpg_ammo' },
  AMMO_STINGER = { item = 'stinger_ammo' },
  AMMO_BALL = { item = 'ball' },
  AMMO_STICKYBOMB = { item = 'stickybomb' },
  AMMO_SMOKEGRENADE = { item = 'smokegrenade' },
  AMMO_BZGAS = { item = 'gzgas_ammo' },
  AMMO_FLARE = { item = 'flare_ammo' },
  AMMO_MOLOTOV = { item = 'molotov' },
  AMMO_TANK = { item = 'tank_ammo' },
  AMMO_SPACE_ROCKET = { item = 'space_rocket_ammo' },
  AMMO_PLANE_ROCKET = { item = 'plane_rocket_ammo' },
  AMMO_PLAYER_LASER = { item = 'player_laser_ammo' },
  AMMO_ENEMY_LASER = { item = 'enemy_laser_ammo' },
  AMMO_BIRD_CRAP = { item = 'bird_crap_ammo' }
}